# Generated by Django 4.0.5 on 2022-06-06 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('separator', models.CharField(default=',', max_length=1, verbose_name='Separator')),
                ('status', models.CharField(choices=[('Ready', 'Ready to download'), ('Process', 'In progress'), ('Failed', 'Error')], max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Files with data')),
                ('status', models.CharField(blank=True, choices=[('Ready', 'Ready to download'), ('Process', 'In progress'), ('Failed', 'Error')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_files', to='data.data')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('column_type', models.CharField(choices=[('name', 'Full name'), ('integer', 'Number range'), ('date', 'Date time'), ('email', 'E-mail'), ('phone', 'Phone number'), ('job', 'Job')], max_length=30)),
                ('integer_range_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='From')),
                ('integer_range_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='To')),
                ('order', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Column order')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_in_data', to='data.data', verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Column in data',
                'verbose_name_plural': 'Columns in data',
            },
        ),
    ]
